vich_uploader:
    db_driver: orm

    mappings:
        plants_images:
            uri_prefix: '%plants_images%'
            upload_destination: '%kernel.project_dir%/public%plants_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
